#define ALPHA_PATCH 1
#define ANYSIZE_PATCH 1
#define ANYSIZE_NOBAR_PATCH 1
#define VERTCENTER_PATCH 1
#define RELATIVEBORDER_PATCH 1
#define THEMED_CURSOR_PATCH 1
#define HIDECURSOR_PATCH 1
#define SPOILER_PATCH 1
#define NETWMICON_PATCH 1

#define WIDE_GLYPHS_PATCH 1
#define WIDE_GLYPH_SPACING_PATCH 0
#define LIGATURES_PATCH 1
#define BOLD_IS_NOT_BRIGHT_PATCH 1
#define SYNC_PATCH 1

#define BLINKING_CURSOR_PATCH 1
#define OSC_10_11_12_2_PATCH 1
#define UNDERCURL_PATCH 1

#define DELKEY_PATCH 1
#define UNIVERSCROLL_PATCH 1
#define FIXKEYBOARDINPUT_PATCH 0

#define SIXEL_PATCH 1
#define W3M_PATCH 1
#define WORKINGDIR_PATCH 1
#define ST_EMBEDDER_PATCH 1



#define BOXDRAW_PATCH 0
